version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: admin
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d